- repo: https://github.com/prettier/prettier
  rev: "" # Use the sha or tag you want to point at
  hooks:
    - id: prettier
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.3
  hooks:
    - id: seed-isort-config
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
    - id: isort
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      language_version: python3
